// vocab-data.js - Part 1 of 4

const VOCAB_BY_SET = {
    "All Sets": [], // This will be populated dynamically in init()
    "Set 1": [
        { front: "Abhorrent", back: "<strong>Inspiring disgust and loathing.</strong>\n\nExample: The smell of rotten eggs was abhorrent to her.\nSynonyms: Hateful, disgusting" },
        { front: "Abide", back: "<strong>To accept or act in accordance with a rule or decision.</strong>\n\nExample: You must abide by the rules of the library.\nSynonyms: Obey, follow" },
        { front: "Abject", back: "<strong>(Of a situation or condition) extremely bad, unpleasant, and degrading.</strong>\n\nExample: The family lived in abject poverty.\nSynonyms: Miserable, hopeless" },
        { front: "Abolish", back: "<strong>To formally put an end to a system, practice, or institution.</strong>\n\nExample: Slavery was abolished in many countries years ago.\nSynonyms: End, stop" },
        { front: "Abominable", back: "<strong>Causing moral revulsion.</strong>\n\nExample: The abominable weather ruined our picnic.\nSynonyms: Horrible, terrible" },
        { front: "Abridge", back: "<strong>To shorten a book, film, or speech without losing the sense.</strong>\n\nExample: The long novel was abridged into a shorter version for children.\nSynonyms: Shorten, condense" },
        { front: "Abstain", back: "<strong>To choose not to do something.</strong>\n\nExample: She decided to abstain from eating sweets for a month.\nSynonyms: Refrain, avoid" },
        { front: "Abundant", back: "<strong>Existing or available in large quantities; plentiful.</strong>\n\nExample: There was an abundant supply of fresh fruit at the market.\nSynonyms: Plentiful, ample" },
        { front: "Accolade", back: "<strong>An award or privilege granted as a special honour or as an acknowledgment of merit.</strong>\n\nExample: The scientist received an accolade for her groundbreaking research.\nSynonyms: Award, honour" },
        { front: "Accord", back: "<strong>Agreement or harmony.</strong>\n\nExample: The two countries signed a peace accord.\nSynonyms: Agreement, harmony" },
        { front: "Accrue", back: "<strong>(Of a benefit or sum of money) be received by someone in regular or increasing amounts over time.</strong>\n\nExample: Interest will accrue on your savings account.\nSynonyms: Accumulate, gather" }
    ],
    "Set 2": [
        { front: "Acquiesce", back: "<strong>To accept something reluctantly but without protest.</strong>\n\nExample: She reluctantly acquiesced to his demands.\nSynonyms: Agree, consent" },
        { front: "Acrimonious", back: "<strong>(Typically of a speech or debate) angry and bitter.</strong>\n\nExample: The debate was acrimonious, with both sides refusing to compromise.\nSynonyms: Bitter, hostile" },
        { front: "Acumen", back: "<strong>The ability to make good judgments and quick decisions.</strong>\n\nExample: Her business acumen helped her company succeed.\nSynonyms: Sharpness, insight" },
        { front: "Adamant", back: "<strong>Refusing to be persuaded or to change one's mind.</strong>\n\nExample: He was adamant that he was right and wouldn't listen to anyone else.\nSynonyms: Stubborn, unyielding" },
        { front: "Admonish", back: "<strong>To warn or reprimand someone firmly.</strong>\n\nExample: The teacher admonished the student for talking during the lesson.\nSynonyms: Reprimand, scold" },
        { front: "Adorn", back: "<strong>To decorate or enhance.</strong>\n\nExample: She adorned her hair with beautiful flowers.\nSynonyms: Decorate, embellish" },
        { front: "Adversary", back: "<strong>One's opponent in a contest, conflict, or dispute.</strong>\n\nExample: He faced his old adversary in the chess championship.\nSynonyms: Opponent, enemy" },
        { front: "Affable", back: "<strong>Friendly, good-natured, or easy to talk to.</strong>\n\nExample: The new teacher was very affable and approachable.\nSynonyms: Friendly, amiable" },
        { front: "Affected", back: "<strong>Influenced or changed by something.</strong>\n\nExample: His mood was affected by the rainy weather.\nSynonyms: Impacted, influenced" },
        { front: "Affluent", back: "<strong>Having a great deal of money; wealthy.</strong>\n\nExample: The affluent neighborhood had large houses and expensive cars.\nSynonyms: Wealthy, rich" },
        { front: "Aggravate", back: "<strong>To make a problem, injury, or offence worse or more serious.</strong>\n\nExample: The loud noise started to aggravate his headache.\nSynonyms: Worsen, annoy" },
        { front: "Allure", back: "<strong>The quality of being powerfully attractive or fascinating.</strong>\n\nExample: The allure of adventure led him to travel the world.\nSynonyms: Attraction, charm" }
    ],
    "Set 3": [
        { front: "Ambrosial", back: "<strong>Tasting or smelling very delicious.</strong>\n\nExample: The bakery was filled with the ambrosial scent of freshly baked bread.\nSynonyms: delicious, tasty" },
        { front: "Ample", back: "<strong>More than enough; plenty.</strong>\n\nExample: There was ample space in the playground for all the children to run around.\nSynonyms: plentiful, large" },
        { front: "Antiquated", back: "<strong>Very old and not used much anymore.</strong>\n\nExample: The school had an antiquated computer that didn't even have the internet!\nSynonyms: old-fashioned, outdated" },
        { front: "Apathy", back: "<strong>Not caring about something.</strong>\n\nExample: Tom showed apathy towards his homework and didn't even try to finish it.\nSynonyms: laziness, indifference" },
        { front: "Appreciate", back: "<strong>To be thankful for something or to understand its value.</strong>\n\nExample: I appreciate all the hard work my teacher does to help me learn.\nSynonyms: value, be grateful" },
        { front: "Apprehensive", back: "<strong>Feeling nervous or worried about something.</strong>\n\nExample: Emma felt apprehensive before her big test, but she did well in the end.\nSynonyms: nervous, anxious" },
        { front: "Arduous", back: "<strong>Very hard and needing a lot of effort.</strong>\n\nExample: Climbing the tall mountain was an arduous journey.\nSynonyms: difficult, tiring" },
        { front: "Argument", back: "<strong>A disagreement where people have different opinions.</strong>\n\nExample: The two friends had an argument about which game to play at lunchtime.\nSynonyms: disagreement, dispute" },
        { front: "Arid", back: "<strong>Very dry, with little or no rain.</strong>\n\nExample: The desert is an arid place where very few plants grow.\nSynonyms: dry, barren" },
        { front: "Artful", back: "<strong>Clever or skilful in a tricky way.</strong>\n\nExample: The artful magician amazed the crowd with his tricks.\nSynonyms: clever, crafty" },
        { front: "Articulate", back: "<strong>Able to speak clearly and explain things well.</strong>\n\nExample: Lily is very articulate when she presents her ideas in class.\nSynonyms: clear, expressive" }
    ],
    "Set 4": [
        { front: "Artisan", back: "<strong>A person who is very skilled at making things by hand.</strong>\n\nExample: The artisan carefully carved a beautiful wooden statue.\nSynonyms: Craftsperson, Maker" },
        { front: "Ashamed", back: "<strong>Feeling bad or guilty about something you did.</strong>\n\nExample: Mia was ashamed when she forgot to do her homework.\nSynonyms: Embarrassed, Guilty" },
        { front: "Assemble", back: "<strong>To put things together to make something.</strong>\n\nExample: We had to assemble the puzzle before we could see the full picture.\nSynonyms: Build, Gather" },
        { front: "Asunder", back: "<strong>Broken into pieces or pulled apart.</strong>\n\nExample: The old bridge was torn asunder by the strong storm.\nSynonyms: Apart, Split" },
        { front: "Augur", back: "<strong>To show that something good or bad might happen in the future.</strong>\n\nExample: Dark clouds augur that a storm is coming.\nSynonyms: Predict, Foretell" },
        { front: "Attempt", back: "<strong>To try to do something.</strong>\n\nExample: Ben made an attempt to climb the tree but slipped halfway.\nSynonyms: Try, Effort" },
        { front: "Austerity", back: "<strong>Living in a very simple way, without extra things.</strong>\n\nExample: During the war, people had to live with austerity and use fewer resources.\nSynonyms: Simplicity, Strictness" },
        { front: "Aversion", back: "<strong>A strong dislike for something.</strong>\n\nExample: Sam has an aversion to spicy food and never eats it.\nSynonyms: Dislike, Hatred" },
        { front: "Avoid", back: "<strong>To stay away from something or someone.</strong>\n\nExample: I try to avoid stepping on puddles when walking to school.\nSynonyms: Stay away, Escape" },
        { front: "Avuncular", back: "<strong>Being kind and friendly like an uncle.</strong>\n\nExample: Mr. Jones had an avuncular smile that made the children feel safe.\nSynonyms: Friendly, Kind" },
        { front: "Barbaric", back: "<strong>Very cruel or violent.</strong>\n\nExample: The king's barbaric punishment frightened the villagers.\nSynonyms: Savage, Brutal" }
    ],
    "Set 5": [
        { front: "Beneficial", back: "<strong>Good for you; helpful.</strong>\n\nExample: Eating vegetables is very beneficial for your health.\nSynonyms: Helpful, advantageous" },
        { front: "Benevolent", back: "<strong>Kind and generous.</strong>\n\nExample: The benevolent old woman always donated to charity.\nSynonyms: Kind, compassionate" },
        { front: "Bewildered", back: "<strong>Completely confused and puzzled.</strong>\n\nExample: The new student looked bewildered in the crowded hallway.\nSynonyms: Confused, puzzled" },
        { front: "Bias", back: "<strong>A strong feeling for or against something or someone, often unfairly.</strong>\n\nExample: The judge tried to be fair and not show any bias.\nSynonyms: Prejudice, favoritism" },
        { front: "Bigoted", back: "<strong>Having very strong, unfair opinions about a group of people.</strong>\n\nExample: His bigoted comments showed he was unwilling to accept others' beliefs.\nSynonyms: Prejudiced, intolerant" },
        { front: "Bilk", back: "<strong>To cheat someone out of money.</strong>\n\nExample: The con artist tried to bilk the old man out of his savings.\nSynonyms: Cheat, swindle" },
        { front: "Bizarre", back: "<strong>Very strange or unusual.</strong>\n\nExample: The magician performed a bizarre trick that no one could explain.\nSynonyms: Strange, odd" },
        { front: "Blasphemy", back: "<strong>Disrespectful talk or actions about sacred things.</strong>\n\nExample: His joke about the ancient rituals was considered blasphemy by some.\nSynonyms: Sacrilege, irreverence" },
        { front: "Bleak", back: "<strong>(Of a place or weather) cold, dismal, and unwelcoming; (of a situation) not hopeful or encouraging.</strong>\n\nExample: The winter landscape was bleak and grey.\nSynonyms: Gloomy, grim" },
        { front: "Bliss", back: "<strong>Complete happiness.</strong>\n\nExample: Lying on the beach felt like pure bliss.\nSynonyms: Joy, ecstasy" }
    ],
    "Set 6": [
        { front: "Blissful", back: "<strong>Full of happiness and joy.</strong>\n\nExample: She felt blissful as she lay on the beach, listening to the waves.\nSynonyms: joyful, content" },
        { front: "Blunder", back: "<strong>A careless or foolish mistake.</strong>\n\nExample: He made a terrible blunder by forgetting his best friend's birthday.\nSynonyms: mistake, error" },
        { front: "Bolster", back: "<strong>To support or strengthen.</strong>\n\nExample: The teacher bolstered the student's confidence by praising his hard work.\nSynonyms: reinforce, support" },
        { front: "Bravado", back: "<strong>A bold manner intended to impress or intimidate.</strong>\n\nExample: His bravado disappeared when he realised how high the cliff was.\nSynonyms: swagger, confidence" },
        { front: "Brawn", back: "<strong>Physical strength.</strong>\n\nExample: It took a lot of brawn to lift the heavy box.\nSynonyms: muscle, power" },
        { front: "Brusque", back: "<strong>Abrupt or blunt in manner.</strong>\n\nExample: The brusque reply made it clear he was in no mood to talk.\nSynonyms: curt, abrupt" },
        { front: "Cache", back: "<strong>A hidden store of things, especially valuables.</strong>\n\nExample: The pirates hid their cache of treasure on the deserted island.\nSynonyms: hoard, stash" },
        { front: "Calamity", back: "<strong>A disaster or great misfortune.</strong>\n\nExample: The flood was a calamity that left many people homeless.\nSynonyms: disaster, catastrophe" },
        { front: "Candid", back: "<strong>Truthful and straightforward.</strong>\n\nExample: She gave a candid answer, even though it wasn't what he wanted to hear.\nSynonyms: honest, frank" },
        { front: "Candidate", back: "<strong>A person who applies for a job or is nominated for a position.</strong>\n\nExample: There were three candidates running for school council president.\nSynonyms: applicant, nominee" },
        { front: "Career", back: "<strong>A long-term job or profession.</strong>\n\nExample: He wanted a career in medicine because he loved helping people.\nSynonyms: profession, occupation" },
        { front: "Charismatic", back: "<strong>Charming and able to attract and influence people.</strong>\n\nExample: The charismatic speaker captivated the entire audience.\nSynonyms: charming, persuasive" }
    ],
    "Set 7": [
        { front: "Charming", back: "<strong>Very pleasing or attractive.</strong>\n\nExample: The charming little cottage was surrounded by colorful flowers.\nSynonyms: Enchanting, delightful" },
        { front: "Charred", back: "<strong>Burned or blackened due to heat.</strong>\n\nExample: The toast was so charred that it was completely inedible.\nSynonyms: Scorched, blackened" },
        { front: "Coerce", back: "<strong>To force someone to do something against their will.</strong>\n\nExample: The bully tried to coerce his classmates into giving him their lunch money.\nSynonyms: Compel, pressure" },
        { front: "Coherent", back: "<strong>Logical and easy to understand.</strong>\n\nExample: The teacher praised Jake's essay for being clear and coherent.\nSynonyms: Logical, consistent" },
        { front: "Colloquial", back: "<strong>Informal or conversational in language.</strong>\n\nExample: His speech was filled with colloquial expressions that made it sound casual.\nSynonyms: Informal, conversational" },
        { front: "Combination", back: "<strong>A mixture of different things put together.</strong>\n\nExample: The cake was a delicious combination of chocolate and vanilla flavors.\nSynonyms: Mixture, blend" },
        { front: "Comical", back: "<strong>Funny or amusing.</strong>\n\nExample: The clown's comical antics made everyone laugh.\nSynonyms: Humorous, amusing" },
        { front: "Commemorate", back: "<strong>To honor or remember someone or something.</strong>\n\nExample: The school held a special event to commemorate its 50th anniversary.\nSynonyms: Celebrate, honor" },
        { front: "Compel", back: "<strong>To force someone to do something.</strong>\n\nExample: The strong wind seemed to compel us to move faster.\nSynonyms: Force, urge" },
        { front: "Compliance", back: "<strong>The act of following rules or orders.</strong>\n\nExample: The company ensured compliance with safety regulations.\nSynonyms: Obedience, conformity" },
        { front: "Comrade", back: "<strong>A friend, especially one who shares similar interests or experiences.</strong>\n\nExample: The soldiers treated each other as comrades, always looking out for one another.\nSynonyms: Companion, ally" }
    ],
    "Set 8": [
        { front: "Conceited", back: "<strong>Having an excessively favorable opinion of one's own ability or appearance.</strong>\n\nExample: She was so conceited that she thought she was the best at everything.\nSynonyms: arrogant, boastful" },
        { front: "Conclusion", back: "<strong>The end or finish of an event or process.</strong>\n\nExample: At the conclusion of the story, the hero saved the day.\nSynonyms: ending, final part" },
        { front: "Conclusive", back: "<strong>Providing something that is certain and final.</strong>\n\nExample: The scientist found conclusive evidence that proved the theory.\nSynonyms: definite, certain" },
        { front: "Concur", back: "<strong>To agree with someone or something.</strong>\n\nExample: I concur with your idea because it makes sense.\nSynonyms: agree, support" },
        { front: "Condemn", back: "<strong>To express complete disapproval of, typically in public.</strong>\n\nExample: The teacher had to condemn the rude behavior in class.\nSynonyms: criticise, punish" },
        { front: "Condone", back: "<strong>To accept and allow (behavior that is considered wrong or offensive) to continue.</strong>\n\nExample: The school does not condone bullying of any kind.\nSynonyms: allow, accept" },
        { front: "Conducive", back: "<strong>Making a certain situation or outcome likely or possible.</strong>\n\nExample: A quiet classroom is conducive to learning.\nSynonyms: helpful, beneficial" },
        { front: "Confiscated", back: "<strong>Taken or seized with authority.</strong>\n\nExample: The teacher confiscated the toy because it was distracting the class.\nSynonyms: took away, seize" },
        { front: "Conjecture", back: "<strong>An opinion or conclusion based on incomplete information.</strong>\n\nExample: His idea was just a conjecture since he had no proof.\nSynonyms: guess, prediction" },
        { front: "Consent", back: "<strong>Permission for something to happen or agreement to do something.</strong>\n\nExample: You need a parent's consent to go on the school trip.\nSynonyms: permission, approval" },
        { front: "Consequently", back: "<strong>As a result; therefore.</strong>\n\nExample: He forgot his homework; consequently, he had to stay in at break.\nSynonyms: therefore, as a result" },
        { front: "Consideration", back: "<strong>Thoughtfulness for other people's feelings and well-being.</strong>\n\nExample: Out of consideration for others, she spoke quietly in the library.\nSynonyms: kindness, thoughtfulness" }
    ],
    "Set 9": [
        { front: "Conspire", back: "<strong>To secretly plan something unlawful or harmful with others.</strong>\n\nExample: The rebels conspired to overthrow the government.\nSynonyms: plot, scheme" },
        { front: "Consume", back: "<strong>To use up or eat/drink something.</strong>\n\nExample: The fire consumed the entire building within hours.\nSynonyms: devour, absorb" },
        { front: "Contagious", back: "<strong>Spreading easily from one person to another.</strong>\n\nExample: Laughter is often contagious, making everyone around join in.\nSynonyms: infectious, transmissible" },
        { front: "Contemporary", back: "<strong>Existing or happening at the same time; modern.</strong>\n\nExample: Many contemporary artists experiment with digital media.\nSynonyms: modern, present-day" },
        { front: "Contrast", back: "<strong>A clear difference between two things.</strong>\n\nExample: The bright colours contrast sharply with the dark background.\nSynonyms: difference, distinction" },
        { front: "Contrite", back: "<strong>Feeling deep guilt and remorse for wrongdoing.</strong>\n\nExample: He gave a contrite apology for his rude behaviour.\nSynonyms: remorseful, repentant" },
        { front: "Conundrum", back: "<strong>A difficult problem or puzzle.</strong>\n\nExample: Deciding whether to move abroad or stay at home was a real conundrum.\nSynonyms: puzzle, dilemma" },
        { front: "Convict", back: "<strong>To declare someone guilty of a crime.</strong>\n\nExample: The jury decided to convict the suspect after reviewing the evidence.\nSynonyms: sentence, condemn" },
        { front: "Cordial", back: "<strong>Warm and friendly.</strong>\n\nExample: The hotel staff gave us a cordial welcome upon arrival.\nSynonyms: friendly, gracious" },
        { front: "Covet", back: "<strong>To strongly desire something that belongs to someone else.</strong>\n\nExample: She coveted her friend's designer handbag.\nSynonyms: desire, yearn for" },
        { front: "Coy", back: "<strong>Pretending to be shy or reserved.</strong>\n\nExample: She gave a coy smile when asked about her new boyfriend.\nSynonyms: shy, bashful" }
    ],
    "Set 10": [
        { front: "Crass", back: "<strong>Lacking sensitivity or intelligence.</strong>\n\nExample: His crass joke offended everyone at the dinner table.\nSynonyms: insensitive, tactless" },
        { front: "Credit", back: "<strong>Praise or recognition for something well done.</strong>\n\nExample: She received full credit for her hard work on the project.\nSynonyms: recognition, acknowledgment" },
        { front: "Cunning", back: "<strong>Clever at achieving goals, often by deceit.</strong>\n\nExample: The cunning fox tricked the farmer and stole his chickens.\nSynonyms: sly, crafty" },
        { front: "Curb", back: "<strong>To control or limit something.</strong>\n\nExample: He tried to curb his appetite by eating healthy snacks.\nSynonyms: restrain, restrict" },
        { front: "Curious", back: "<strong>Eager to learn or know something.</strong>\n\nExample: The curious child kept asking questions about space.\nSynonyms: inquisitive, questioning" },
        { front: "Curt", back: "<strong>Rudely brief or abrupt.</strong>\n\nExample: His curt reply made it clear he didn't want to talk.\nSynonyms: brusque, terse" },
        { front: "Dazzling", back: "<strong>Extremely bright or impressive.</strong>\n\nExample: The fireworks created a dazzling display in the night sky.\nSynonyms: brilliant, radiant" },
        { front: "Debate", back: "<strong>A formal discussion or argument on a topic.</strong>\n\nExample: The students had a debate about the effects of technology on society.\nSynonyms: discussion, dispute" },
        { front: "Decline", back: "<strong>To refuse or decrease.</strong>\n\nExample: She had to decline the invitation due to prior commitments.\nSynonyms: reject, diminish" },
        { front: "Definite", back: "<strong>Clear and certain.</strong>\n\nExample: There was a definite improvement in his performance after training.\nSynonyms: clear, absolute" },
        { front: "Defy", back: "<strong>To resist or refuse to obey.</strong>\n\nExample: The protesters chose to defy the new law by marching in the streets.\nSynonyms: Challenge, Resist" },
        { front: "Deject", back: "<strong>To make someone feel sad or disheartened.</strong>\n\nExample: Losing the championship left the team feeling dejected.\nSynonyms: Depress, Dishearten" },
        { front: "Deluge", back: "<strong>A great flood or an overwhelming amount of something.</strong>\n\nExample: The sudden deluge of emails overwhelmed her inbox.\nSynonyms: Flood, Overflow" }
    ],
    // vocab-data.js - Part 2 of 4

    "Set 11": [
        { front: "Demolish", back: "<strong>To destroy or tear something down completely.</strong>\n\nExample: The old house was demolished to make space for a new shopping mall.\nSynonyms: Destroy, Wreck" },
        { front: "Demure", back: "<strong>(Of a woman or her behavior) reserved, modest, and shy.</strong>\n\nExample: She gave him a demure smile and looked down shyly.\nSynonyms: Modest, reserved" },
        { front: "Denounce", back: "<strong>To publicly declare something to be wrong or evil.</strong>\n\nExample: The politician was quick to denounce the acts of violence.\nSynonyms: Condemn, criticize" },
        { front: "Depict", back: "<strong>To represent something in art, literature, or a description.</strong>\n\nExample: The painting depicts a beautiful landscape with rolling hills.\nSynonyms: Portray, show" },
        { front: "Depraved", back: "<strong>Morally corrupt; wicked.</strong>\n\nExample: The villain's depraved actions shocked everyone in the story.\nSynonyms: Corrupt, evil" },
        { front: "Derelict", back: "<strong>(Of a building or land) in a very poor condition as a result of disuse and neglect.</strong>\n\nExample: The old factory stood derelict for years before it was torn down.\nSynonyms: Abandoned, run-down" },
        { front: "Derogatory", back: "<strong>Showing a critical or disrespectful attitude.</strong>\n\nExample: He made a derogatory remark about her clothes, which made her upset.\nSynonyms: Insulting, disparaging" },
        { front: "Desecrate", back: "<strong>To treat a sacred place or thing with violent disrespect.</strong>\n\nExample: Vandals desecrated the ancient monument with graffiti.\nSynonyms: Defile, profane" },
        { front: "Despicable", back: "<strong>Deserving hatred and contempt.</strong>\n\nExample: His despicable behavior made him an outcast among his friends.\nSynonyms: Contemptible, vile" },
        { front: "Destitute", back: "<strong>Without money, food, a home, or possessions.</strong>\n\nExample: After losing everything, the family was left destitute.\nSynonyms: Impoverished, penniless" },
        { front: "Detrimental", back: "<strong>Causing harm or damage.</strong>\n\nExample: Smoking has many detrimental effects on health.\nSynonyms: Harmful, damaging" },
        { front: "Devour", back: "<strong>To eat (food or prey) hungrily or quickly.</strong>\n\nExample: The hungry wolf devoured its meal in minutes.\nSynonyms: Consume, gobble" }
    ],
    "Set 12": [
        { front: "Diligent", back: "<strong>Having or showing care and conscientiousness in one's work or duties.</strong>\n\nExample: She was a diligent student who always submitted her homework on time.\nSynonyms: Industrious, hardworking" },
        { front: "Diminish", back: "<strong>To make or become less.</strong>\n\nExample: The pain in his leg began to diminish after he took medicine.\nSynonyms: Reduce, decrease" },
        { front: "Disdain", back: "<strong>The feeling that someone or something is unworthy of one's consideration or respect.</strong>\n\nExample: She looked at the messy room with disdain.\nSynonyms: Contempt, scorn" },
        { front: "Disheveled", back: "<strong>(Of a person's hair, clothes, or appearance) untidy; disordered.</strong>\n\nExample: After a long journey, he looked tired and disheveled.\nSynonyms: Untidy, messy" },
        { front: "Dismal", back: "<strong>Depressing; dreary.</strong>\n\nExample: The dismal weather made everyone feel sad.\nSynonyms: Gloomy, dreary" },
        { front: "Disparage", back: "<strong>To regard or represent as being of little worth.</strong>\n\nExample: It's unkind to disparage someone's efforts, even if they aren't perfect.\nSynonyms: Belittle, deprecate" },
        { front: "Disparity", back: "<strong>A great difference.</strong>\n\nExample: There is a great disparity between the rich and the poor.\nSynonyms: Difference, imbalance" },
        { front: "Dispute", back: "<strong>A disagreement, argument, or debate.</strong>\n\nExample: The two friends had a dispute over who broke the toy.\nSynonyms: Argument, disagreement" },
        { front: "Disrupt", back: "<strong>To interrupt an event, activity, or process by causing a disturbance or problem.</strong>\n\nExample: The loud noise outside began to disrupt the class.\nSynonyms: Interrupt, disturb" },
        { front: "Dissent", back: "<strong>The expression or holding of opinions contrary to those previously, commonly, or officially expressed.</strong>\n\nExample: There was strong public dissent against the new tax laws.\nSynonyms: Disagreement, opposition" },
        { front: "Distraught", back: "<strong>Deeply upset and agitated.</strong>\n\nExample: She was distraught after losing her beloved pet.\nSynonyms: Upset, agitated" },
        { front: "Docile", back: "<strong>Ready to accept control or instruction; submissive.</strong>\n\nExample: The docile puppy quickly learned new tricks.\nSynonyms: Obedient, submissive" }
    ],
    "Set 13": [
        { front: "Domineering", back: "<strong>Asserting one's will over another in an arrogant way.</strong>\n\nExample: The domineering boss always told everyone what to do.\nSynonyms: Bossy, overbearing" },
        { front: "Drab", back: "<strong>Lacking brightness or interest; dull.</strong>\n\nExample: The old house was painted in a drab grey color.\nSynonyms: Dull, plain" },
        { front: "Dreadful", back: "<strong>Causing or involving great suffering, fear, or unhappiness; extremely bad or serious.</strong>\n\nExample: The dreadful storm kept us awake all night.\nSynonyms: Terrible, awful" },
        { front: "Dubious", back: "<strong>Hesitating or doubting; not to be relied upon.</strong>\n\nExample: He made a dubious claim that he had seen a dinosaur.\nSynonyms: Doubtful, suspicious" },
        { front: "Dwindle", back: "<strong>To diminish gradually in size, amount, or strength.</strong>\n\nExample: The number of students in the club began to dwindle.\nSynonyms: Decrease, shrink" },
        { front: "Eager", back: "<strong>Wanting to do or have something very much.</strong>\n\nExample: The children were eager to open their presents.\nSynonyms: Keen, excited" },
        { front: "Eccentric", back: "<strong>(Of a person or their behavior) unconventional and slightly strange.</strong>\n\nExample: The eccentric old man always wore a hat covered in feathers.\nSynonyms: Quirky, odd" },
        { front: "Ecstatic", back: "<strong>Feeling or expressing overwhelming happiness or joyful excitement.</strong>\n\nExample: She was ecstatic when she heard she won the competition.\nSynonyms: Overjoyed, thrilled" },
        { front: "Edict", back: "<strong>An official order or proclamation issued by a person in authority.</strong>\n\nExample: The king issued an edict that all citizens must pay new taxes.\nSynonyms: Decree, order" },
        { front: "Eerie", back: "<strong>Strange and frightening.</strong>\n\nExample: The old, abandoned house had an eerie silence.\nSynonyms: Spooky, ghostly" },
        { front: "Efface", back: "<strong>To erase (a mark) from a surface; to make oneself unnoticeable.</strong>\n\nExample: Time will efface the memory of his troubles.\nSynonyms: Erase, obliterate" }
    ],
    "Set 14": [
        { front: "Elaborate", back: "<strong>Detailed and complicated in design and planning.</strong>\n\nExample: The wedding had an elaborate cake with many layers and decorations.\nSynonyms: Complex, intricate" },
        { front: "Eloquent", back: "<strong>Fluent or persuasive in speaking or writing.</strong>\n\nExample: The politician delivered an eloquent speech that moved the audience.\nSynonyms: Articulate, expressive" },
        { front: "Elusive", back: "<strong>Difficult to find, catch, or achieve.</strong>\n\nExample: The elusive butterfly fluttered away before I could catch it.\nSynonyms: Slippery, fleeting" },
        { front: "Emaciated", back: "<strong>Abnormally thin or weak, especially because of illness or lack of food.</strong>\n\nExample: The rescue dog was emaciated from lack of food.\nSynonyms: Thin, gaunt" },
        { front: "Emanate", back: "<strong>(Of a feeling, quality, or atmosphere) issue or spread out from (a source).</strong>\n\nExample: A sense of peace seemed to emanate from the ancient temple.\nSynonyms: Originate, radiate" },
        { front: "Embellish", back: "<strong>To make (something) more attractive by the addition of decorative details or features.</strong>\n\nExample: She liked to embellish her stories with exciting details.\nSynonyms: Decorate, adorn" },
        { front: "Emphatic", back: "<strong>Showing or giving emphasis; expressing something forcibly and clearly.</strong>\n\nExample: He gave an emphatic nod to show his strong agreement.\nSynonyms: Forceful, firm" },
        { front: "Encumber", back: "<strong>To restrict or burden (someone or something) in such a way that free action or movement is difficult.</strong>\n\nExample: Heavy luggage can encumber a traveler.\nSynonyms: Hinder, burden" },
        { front: "Endeavor", back: "<strong>To try hard to do or achieve something.</strong>\n\nExample: He will endeavor to complete the task before sunset.\nSynonyms: Try, attempt" },
        { front: "Endorse", back: "<strong>To publicly declare one's approval or support of something or someone.</strong>\n\nExample: Many celebrities endorse popular brands.\nSynonyms: Support, approve" },
        { front: "Enduring", back: "<strong>Lasting over a long period; durable.</strong>\n\nExample: The enduring appeal of classic books never fades.\nSynonyms: Lasting, permanent" },
        { front: "Enigmatic", back: "<strong>Difficult to understand; mysterious.</strong>\n\nExample: The enigmatic smile on her face made him wonder what she was thinking.\nSynonyms: Mysterious, puzzling" }
    ],
    "Set 15": [
        { front: "Enmity", back: "<strong>The state or feeling of being actively opposed or hostile to someone or something.</strong>\n\nExample: There has been a long history of enmity between the two rival families.\nSynonyms: Hostility, animosity" },
        { front: "Ensnare", back: "<strong>To catch in or as in a trap.</strong>\n\nExample: The cunning hunter tried to ensnare the wild animal.\nSynonyms: Trap, capture" },
        { front: "Entice", back: "<strong>To attract or tempt by offering pleasure or advantage.</strong>\n\nExample: The sweet smell of the cake was enough to entice her into the kitchen.\nSynonyms: Tempt, lure" },
        { front: "Envisage", back: "<strong>To form a mental picture of something not yet existing or known.</strong>\n\nExample: It's hard to envisage a world without electricity.\nSynonyms: Imagine, foresee" },
        { front: "Ephemeral", back: "<strong>Lasting for a very short time.</strong>\n\nExample: The beauty of a sunset is ephemeral, fading quickly.\nSynonyms: Short-lived, transient" },
        { front: "Equitable", back: "<strong>Fair and impartial.</strong>\n\nExample: The teacher tried to be equitable in distributing treats among the students.\nSynonyms: Fair, just" },
        { front: "Eradicate", back: "<strong>To destroy completely; put an end to.</strong>\n\nExample: Scientists are working to eradicate diseases like malaria.\nSynonyms: Eliminate, destroy" },
        { front: "Erratic", back: "<strong>Not regular or consistent in movement or behavior; unpredictable.</strong>\n\nExample: The car's erratic movements made the passenger nervous.\nSynonyms: Unpredictable, inconsistent" },
        { front: "Ethereal", back: "<strong>Extremely delicate and light in a way that seems too perfect for this world.</strong>\n\nExample: The ballerina's movements were so graceful and ethereal.\nSynonyms: Delicate, ghostly" },
        { front: "Evade", back: "<strong>To escape or avoid, especially by cleverness or trickery.</strong>\n\nExample: The suspect tried to evade capture by hiding in the crowd.\nSynonyms: Avoid, escape" },
        { front: "Evident", back: "<strong>Clearly seen or understood; obvious.</strong>\n\nExample: It was evident from her tears that she was very sad.\nSynonyms: Obvious, clear" }
    ],
    "Set 16": [
        { front: "Exacerbate", back: "<strong>To make a problem, bad situation, or negative feeling worse.</strong>\n\nExample: His rude comments only served to exacerbate the tension.\nSynonyms: Worsen, aggravate" },
        { front: "Exasperated", back: "<strong>Intensely irritated and frustrated.</strong>\n\nExample: The teacher was exasperated by the class's constant talking.\nSynonyms: Frustrated, annoyed" },
        { front: "Exemplary", back: "<strong>Serving as a desirable model; representing the best of its kind.</strong>\n\nExample: Her exemplary behavior earned her a special award.\nSynonyms: Model, perfect" },
        { front: "Exhaustive", back: "<strong>Examining, including, or considering all elements or aspects; fully comprehensive.</strong>\n\nExample: They conducted an exhaustive search of the entire area.\nSynonyms: Thorough, comprehensive" },
        { front: "Exhilarating", back: "<strong>Making one feel very happy, animated, or thrilled; exciting.</strong>\n\nExample: Skydiving was an exhilarating experience.\nSynonyms: Thrilling, exciting" },
        { front: "Exodus", back: "<strong>A mass departure of people.</strong>\n\nExample: There was a mass exodus of people from the city before the hurricane hit.\nSynonyms: Departure, evacuation" },
        { front: "Expedient", back: "<strong>(Of an action) convenient and practical, although possibly improper or immoral.</strong>\n\nExample: It was more expedient to take the shortcut, even though it was muddy.\nSynonyms: Convenient, advantageous" },
        { front: "Explicit", back: "<strong>Stated clearly and in detail, leaving no room for confusion or doubt.</strong>\n\nExample: The instructions were explicit, so there was no confusion.\nSynonyms: Clear, precise" },
        { front: "Exquisite", back: "<strong>Extremely beautiful and delicate.</strong>\n\nExample: She wore an exquisite diamond necklace.\nSynonyms: Beautiful, delicate" },
        { front: "Extol", back: "<strong>To praise enthusiastically.</strong>\n\nExample: The coach would often extol the virtues of teamwork.\nSynonyms: Praise, acclaim" },
        { front: "Extraneous", back: "<strong>Irrelevant or unrelated to the subject being dealt with.</strong>\n\nExample: We removed all the extraneous details from the report.\nSynonyms: Irrelevant, superfluous" }
    ],
    "Set 17": [
        { front: "Fabricate", back: "<strong>To invent or concoct (something), typically with deceitful intent.</strong>\n\nExample: He fabricated a story about being sick to avoid school.\nSynonyms: Invent, concoct" },
        { front: "Facetious", back: "<strong>Treating serious issues with deliberately inappropriate humor; flippant.</strong>\n\nExample: His facetious remarks were not appreciated during the serious meeting.\nSynonyms: Frivolous, playful" },
        { front: "Familiar", back: "<strong>Well known or recognized.</strong>\n\nExample: The melody of the song was very familiar to me.\nSynonyms: Well-known, customary" },
        { front: "Farcical", back: "<strong>Relating to or resembling a farce; ludicrously absurd.</strong>\n\nExample: The whole situation turned into a farcical comedy of errors.\nSynonyms: Absurd, ridiculous" },
        { front: "Fastidious", back: "<strong>Very attentive to and concerned about accuracy and detail.</strong>\n\nExample: He was fastidious about keeping his room perfectly clean.\nSynonyms: Meticulous, fussy" },
        { front: "Fathom", back: "<strong>To understand (a difficult problem or an enigmatic person) after much thought.</strong>\n\nExample: I can't fathom why he would do such a thing.\nSynonyms: Understand, comprehend" },
        { front: "Feasible", back: "<strong>Possible to do easily or conveniently.</strong>\n\nExample: Building a bridge across the river seemed like a feasible plan.\nSynonyms: Possible, practicable" },
        { front: "Fervent", back: "<strong>Having or displaying a passionate intensity.</strong>\n\nExample: She was a fervent supporter of animal rights.\nSynonyms: Passionate, intense" },
        { front: "Fickle", back: "<strong>Changing frequently, especially as regards one's loyalties, interests, or affection.</strong>\n\nExample: The weather in spring can be very fickle, changing from sunny to rainy quickly.\nSynonyms: Changeable, inconsistent" },
        { front: "Fictitious", back: "<strong>Not real or true; imaginary or fabricated.</strong>\n\nExample: The characters in the novel were entirely fictitious.\nSynonyms: Imaginary, false" },
        { front: "Flagrant", back: "<strong>(Of an action considered wrong or immoral) conspicuously or obviously offensive.</strong>\n\nExample: It was a flagrant violation of the rules.\nSynonyms: Blatant, obvious" }
    ],
    "Set 18": [
        { front: "Flourish", back: "<strong>To grow or develop in a healthy or vigorous way, especially as the result of a particularly favorable environment.</strong>\n\nExample: The plants flourished in the warm sunshine.\nSynonyms: Thrive, prosper" },
        { front: "Flout", back: "<strong>To openly disregard (a rule, law, or convention).</strong>\n\nExample: Some drivers flout traffic laws by speeding.\nSynonyms: Defy, disregard" },
        { front: "Foil", back: "<strong>To prevent (something considered wrong or undesirable) from succeeding.</strong>\n\nExample: The hero managed to foil the villain's evil plan.\nSynonyms: Thwart, frustrate" },
        { front: "Foreboding", back: "<strong>A feeling that something bad will happen; fearful apprehension.</strong>\n\nExample: A sense of foreboding filled the air before the storm.\nSynonyms: Apprehension, dread" },
        { front: "Forfeit", back: "<strong>To lose or be deprived of (property or a right or privilege) as a penalty for wrongdoing.</strong>\n\nExample: He had to forfeit his deposit because he cancelled his booking late.\nSynonyms: Lose, surrender" },
        { front: "Fragile", back: "<strong>(Of an object) easily broken or damaged.</strong>\n\nExample: The antique vase was very fragile and had to be handled carefully.\nSynonyms: Delicate, breakable" },
        { front: "Frail", back: "<strong>(Of a person) weak and delicate.</strong>\n\nExample: The old man was frail and needed help walking.\nSynonyms: Weak, delicate" },
        { front: "Frenetic", back: "<strong>Fast and energetic in a rather wild and uncontrolled way.</strong>\n\nExample: The market was a scene of frenetic activity before the holidays.\nSynonyms: Frantic, hectic" },
        { front: "Frivolous", back: "<strong>Not having any serious purpose or value.</strong>\n\nExample: She spent her money on frivolous things like fancy hats.\nSynonyms: Trivial, silly" },
        { front: "Frugal", back: "<strong>Economical with regard to money or food; careful with spending.</strong>\n\nExample: They lived a frugal life, saving money wherever they could.\nSynonyms: Thrifty, economical" },
        { front: "Futile", back: "<strong>Incapable of producing any useful result; pointless.</strong>\n\nExample: It was futile to argue with him because he never changed his mind.\nSynonyms: Useless, pointless" }
    ],
    "Set 19": [
        { front: "Garrulous", back: "<strong>Excessively talkative, especially on trivial matters.</strong>\n\nExample: The garrulous old man told us stories for hours.\nSynonyms: Talkative, chatty" },
        { front: "Generate", back: "<strong>To produce or create.</strong>\n\nExample: The wind turbines generate electricity for the town.\nSynonyms: Create, produce" },
        { front: "Genesis", back: "<strong>The origin or mode of formation of something.</strong>\n\nExample: The genesis of his idea came from a dream.\nSynonyms: Origin, beginning" },
        { front: "Genuine", back: "<strong>Truly what something is said to be; authentic.</strong>\n\nExample: She wore a genuine leather jacket.\nSynonyms: Authentic, real" },
        { front: "Ghoulish", back: "<strong>Resembling or characteristic of a ghoul; morbidly interested in death or disaster.</strong>\n\nExample: The ghoulish stories scared the children.\nSynonyms: Gruesome, macabre" },
        { front: "Glimmer", back: "<strong>A faint or wavering light; a faint manifestation of a feeling or quality.</strong>\n\nExample: We saw a glimmer of hope in the darkness.\nSynonyms: Gleam, flicker" },
        { front: "Gluttonous", back: "<strong>Excessively greedy for food.</strong>\n\nExample: The gluttonous boy ate all the cake by himself.\nSynonyms: Greedy, ravenous" },
        { front: "Gratify", back: "<strong>To give (someone) pleasure or satisfaction.</strong>\n\nExample: It was gratifying to see his hard work pay off.\nSynonyms: Please, satisfy" },
        { front: "Gregarious", back: "<strong>(Of a person) fond of company; sociable.</strong>\n\nExample: She was a gregarious person who loved parties.\nSynonyms: Sociable, outgoing" },
        { front: "Grimace", back: "<strong>An ugly, twisted expression on a person's face, typically expressing disgust, pain, or wry amusement.</strong>\n\nExample: He made a grimace of pain after hitting his thumb.\nSynonyms: Frown, scowl" },
        { front: "Grueling", back: "<strong>Extremely tiring and demanding.</strong>\n\nExample: The marathon was a grueling race that tested the runners' endurance.\nSynonyms: Exhausting, arduous" }
    ],
    "Set 20": [
        { front: "Hallowed", back: "<strong>Regarded as holy and revered.</strong>\n\nExample: The ancient church was a hallowed place of worship.\nSynonyms: Sacred, blessed" },
        { front: "Harass", back: "<strong>To subject to aggressive pressure or intimidation.</strong>\n\nExample: The bullies would harass the younger students every day.\nSynonyms: Pester, annoy" },
        { front: "Hapless", back: "<strong>(Especially of a person) unfortunate.</strong>\n\nExample: The hapless traveller missed his train and was stranded.\nSynonyms: Unlucky, unfortunate" },
        { front: "Haphazard", back: "<strong>Lacking any obvious principle of organization.</strong>\n\nExample: His notes were haphazard, making them difficult to understand.\nSynonyms: Random, unorganized" },
        { front: "Harbinger", back: "<strong>A person or thing that announces or signals the approach of another.</strong>\n\nExample: The robin is a harbinger of spring.\nSynonyms: Herald, indicator" },
        { front: "Hardy", back: "<strong>(Of a person, animal, or plant) robust; capable of enduring difficult conditions.</strong>\n\nExample: The hardy mountain goat could survive in harsh climates.\nSynonyms: Robust, tough" },
        { front: "Hasty", back: "<strong>Done or made with excessive speed or urgency; rushed.</strong>\n\nExample: She made a hasty decision without thinking it through.\nSynonyms: Rushed, quick" },
        { front: "Heed", back: "<strong>To pay attention to; take notice of.</strong>\n\nExample: You should heed your parents' advice.\nSynonyms: Listen, obey" },
        { front: "Heinious", back: "<strong>(Of a criminal act) extremely wicked.</strong>\n\nExample: The criminal was jailed for a heinous crime.\nSynonyms: Wicked, evil" },
        { front: "Herbivore", back: "<strong>An animal that feeds on plants.</strong>\n\nExample: Deer are herbivores, eating only plants.\nSynonyms: Plant-eater" },
        { front: "Hindrance", back: "<strong>A thing that provides resistance, delay, or obstruction to something or someone.</strong>\n\nExample: The loud music was a hindrance to his studying.\nSynonyms: Obstacle, impediment" }
    ],
// vocab-data.js - Part 3 of 4

    "Set 21": [
        { front: "Histrionic", back: "<strong>Overly theatrical or melodramatic in character or style.</strong>\n\nExample: Her histrionic reaction to a small scratch was quite dramatic.\nSynonyms: Theatrical, dramatic" },
        { front: "Hoard", back: "<strong>To accumulate (money or valued objects) and hide or store away.</strong>\n\nExample: Squirrels hoard nuts for the winter.\nSynonyms: Amass, store" },
        { front: "Homage", back: "<strong>Special honour or respect shown publicly.</strong>\n\nExample: The concert was a homage to the late singer.\nSynonyms: Tribute, respect" },
        { front: "Homely", back: "<strong>(Of a place or atmosphere) simple but cozy and comfortable; (of a person) unattractive in appearance.</strong>\n\nExample: The cottage had a homely, inviting feel.\nSynonyms: Cozy, plain" },
        { front: "Hone", back: "<strong>To refine or perfect (something) over a period of time.</strong>\n\nExample: He spent years honing his skills as a painter.\nSynonyms: Sharpen, refine" },
        { front: "Hospitable", back: "<strong>Friendly and welcoming to guests and strangers.</strong>\n\nExample: The villagers were very hospitable, offering us food and shelter.\nSynonyms: Welcoming, generous" },
        { front: "Hostile", back: "<strong>Unfriendly; antagonistic.</strong>\n\nExample: The hostile crowd booed the speaker off the stage.\nSynonyms: Unfriendly, aggressive" },
        { front: "Hubris", back: "<strong>Excessive pride or self-confidence.</strong>\n\nExample: The hero's hubris led to his downfall.\nSynonyms: Arrogance, conceit" },
        { front: "Ignite", back: "<strong>To catch fire or cause to catch fire.</strong>\n\nExample: A spark can easily ignite dry tinder.\nSynonyms: Kindle, inflame" },
        { front: "Ignominious", back: "<strong>Deserving or causing public disgrace or shame.</strong>\n\nExample: The team suffered an ignominious defeat in the final match.\nSynonyms: Humiliating, shameful" },
        { front: "Illicit", back: "<strong>Forbidden by law, rules, or custom.</strong>\n\nExample: They were caught selling illicit goods on the street.\nSynonyms: Illegal, unlawful" }
    ],
    "Set 22": [
        { front: "Immaculate", back: "<strong>Perfectly clean, neat, or tidy.</strong>\n\nExample: Her house was always immaculate, not a speck of dust in sight.\nSynonyms: Spotless, pristine" },
        { front: "Imminent", back: "<strong>About to happen.</strong>\n\nExample: The dark clouds indicated that a storm was imminent.\nSynonyms: Impending, approaching" },
        { front: "Immune", back: "<strong>Protected from a disease or obligation.</strong>\n\nExample: After getting the vaccine, she was immune to the flu.\nSynonyms: Resistant, protected" },
        { front: "Impartial", back: "<strong>Treating all rivals or disputants equally; fair and just.</strong>\n\nExample: A judge must be impartial and fair to both sides.\nSynonyms: Fair, unbiased" },
        { front: "Impediment", back: "<strong>A hindrance or obstruction in doing something.</strong>\n\nExample: His stutter was a slight impediment to his speech.\nSynonyms: Obstacle, barrier" },
        { front: "Imperious", back: "<strong>Assuming power or authority without justification; arrogant and domineering.</strong>\n\nExample: The king's imperious tone left no room for argument.\nSynonyms: Arrogant, dictatorial" },
        { front: "Impetuous", back: "<strong>Acting or done quickly and without thought or care.</strong>\n\nExample: His impetuous decision to quit his job surprised everyone.\nSynonyms: Rash, impulsive" },
        { front: "Impetus", back: "<strong>The force or energy with which a body moves; a driving force.</strong>\n\nExample: The news provided the impetus for him to start working harder.\nSynonyms: Momentum, stimulus" },
        { front: "Implore", back: "<strong>To beg someone earnestly or desperately to do something.</strong>\n\nExample: She implored him to stay, but he still left.\nSynonyms: Beg, plead" },
        { front: "Impromptu", back: "<strong>Done without being planned, organized, or rehearsed.</strong>\n\nExample: They held an impromptu party when their friend announced good news.\nSynonyms: Unplanned, spontaneous" },
        { front: "Impudent", back: "<strong>Not showing due respect for another person; impertinent.</strong>\n\nExample: The impudent child talked back to his elders.\nSynonyms: Insolent, rude" }
    ],
    "Set 23": [
        { front: "Incessant", back: "<strong>(Of something regarded as unpleasant) continuing without pause or interruption.</strong>\n\nExample: The incessant noise from the construction site was annoying.\nSynonyms: Continuous, nonstop" },
        { front: "Incipient", back: "<strong>In an initial stage; beginning to happen or develop.</strong>\n\nExample: The incipient cold symptoms made him feel tired.\nSynonyms: Developing, emerging" },
        { front: "Incite", back: "<strong>To encourage or stir up (violent or unlawful behavior).</strong>\n\nExample: The speaker tried to incite the crowd to protest.\nSynonyms: Provoke, instigate" },
        { front: "Incoherent", back: "<strong>(Of spoken or written language) unclear and difficult to understand.</strong>\n\nExample: After the accident, he was incoherent and couldn't explain what happened.\nSynonyms: Unclear, jumbled" },
        { front: "Incompatible", back: "<strong>(Of two things) unable to exist together or be used in conjunction.</strong>\n\nExample: Their personalities were so incompatible that they often argued.\nSynonyms: Conflicting, mismatched" },
        { front: "Incongruous", back: "<strong>Not in harmony or keeping with the surroundings or other aspects of something.</strong>\n\nExample: A fur coat seemed incongruous in the tropical climate.\nSynonyms: Inappropriate, out of place" },
        { front: "Indignant", back: "<strong>Feeling or showing anger or annoyance at what is perceived as unfair treatment.</strong>\n\nExample: She was indignant at the unfair accusations.\nSynonyms: Annoyed, angry" },
        { front: "Indiscriminate", back: "<strong>Done without careful thought or selection.</strong>\n\nExample: The indiscriminate bombing caused many civilian casualties.\nSynonyms: Random, unselective" },
        { front: "Indolent", back: "<strong>Wanting to avoid activity or exertion; lazy.</strong>\n\nExample: The indolent cat spent all day sleeping in the sun.\nSynonyms: Lazy, idle" },
        { front: "Induce", back: "<strong>To succeed in persuading or influencing (someone) to do something; to bring about or give rise to.</strong>\n\nExample: The doctor induced labor to ensure the baby's safety.\nSynonyms: Persuade, cause" },
        { front: "Ineffectual", back: "<strong>Not producing any or the desired effect.</strong>\n\nExample: His efforts to fix the problem were ineffectual.\nSynonyms: Useless, ineffective" }
    ],
    "Set 24": [
        { front: "Inexorable", back: "<strong>Impossible to stop or prevent.</strong>\n\nExample: The inexorable march of time affects us all.\nSynonyms: Unstoppable, relentless" },
        { front: "Infer", back: "<strong>To deduce or conclude (information) from evidence and reasoning rather than from explicit statements.</strong>\n\nExample: From her tired eyes, I could infer that she hadn't slept well.\nSynonyms: Deduce, conclude" },
        { front: "Inflammatory", back: "<strong>Arousing angry or violent feelings.</strong>\n\nExample: His inflammatory speech sparked protests in the city.\nSynonyms: Provocative, inciting" },
        { front: "Inhibit", back: "<strong>To hinder, restrain, or prevent (an action or process).</strong>\n\nExample: Fear can inhibit people from trying new things.\nSynonyms: Hinder, prevent" },
        { front: "Innocuous", back: "<strong>Not harmful or offensive.</strong>\n\nExample: The spider looked scary but was actually innocuous.\nSynonyms: Harmless, inoffensive" },
        { front: "Inquisitive", back: "<strong>Curious or inquiring.</strong>\n\nExample: The inquisitive child asked many questions about everything.\nSynonyms: Curious, questioning" },
        { front: "Insidious", back: "<strong>Proceeding in a gradual, subtle way, but with harmful effects.</strong>\n\nExample: The insidious disease spread slowly without noticeable symptoms.\nSynonyms: Subtle, treacherous" },
        { front: "Insipid", back: "<strong>Lacking flavour, vigour, or interest.</strong>\n\nExample: The soup was bland and insipid, lacking any seasoning.\nSynonyms: Bland, dull" },
        { front: "Instigate", back: "<strong>To bring about or initiate (an action or event).</strong>\n\nExample: He was accused of trying to instigate a rebellion.\nSynonyms: Incite, provoke" },
        { front: "Insufficient", back: "<strong>Not enough; inadequate.</strong>\n\nExample: The evidence was insufficient to prove his guilt.\nSynonyms: Inadequate, lacking" },
        { front: "Integrity", back: "<strong>The quality of being honest and having strong moral principles; moral uprightness.</strong>\n\nExample: He was known for his integrity and always told the truth.\nSynonyms: Honesty, uprightness" }
    ],
    "Set 25": [
        { front: "Intercede", back: "<strong>To intervene on behalf of another.</strong>\n\nExample: She interceded with the teacher to give her friend more time.\nSynonyms: Mediate, intervene" },
        { front: "Intermittent", back: "<strong>Occurring at irregular intervals; not continuous or steady.</strong>\n\nExample: The rain was intermittent, starting and stopping all afternoon.\nSynonyms: Sporadic, irregular" },
        { front: "Intransigent", back: "<strong>Unwilling or refusing to change one's views or to agree about something.</strong>\n\nExample: He remained intransigent, refusing to compromise on his demands.\nSynonyms: Uncompromising, stubborn" },
        { front: "Intricate", back: "<strong>Very complicated or detailed.</strong>\n\nExample: The clock had an intricate mechanism with many small gears.\nSynonyms: Complex, elaborate" },
        { front: "Intrinsic", back: "<strong>Belonging naturally; essential.</strong>\n\nExample: The intrinsic value of gold makes it precious.\nSynonyms: Essential, inherent" },
        { front: "Inundate", back: "<strong>To overwhelm (someone) with things or people to be dealt with.</strong>\n\nExample: After the commercial, they were inundated with phone calls.\nSynonyms: Overwhelm, flood" },
        { front: "Invert", back: "<strong>To put upside down or in the opposite position.</strong>\n\nExample: He inverted the glass to let it dry.\nSynonyms: Reverse, flip" },
        { front: "Irate", back: "<strong>Feeling or characterized by great anger.</strong>\n\nExample: The irate customer demanded to speak to the manager.\nSynonyms: Furious, enraged" },
        { front: "Jargon", back: "<strong>Special words or expressions used by a profession or group that are difficult for others to understand.</strong>\n\nExample: The medical report was full of jargon that only doctors could understand.\nSynonyms: Terminology, argot" },
        { front: "Jeopardize", back: "<strong>To put (someone or something) into a situation in which there is a danger of loss, harm, or failure.</strong>\n\nExample: Reckless driving can jeopardize your life.\nSynonyms: Endanger, threaten" },
        { front: "Jocular", back: "<strong>Fond of joking; humorous or playful.</strong>\n\nExample: His jocular mood made everyone in the room laugh.\nSynonyms: Humorous, playful" }
    ],
    "Set 26": [
        { front: "Judicious", back: "<strong>Having, showing, or done with good judgment or sense.</strong>\n\nExample: It was a judicious decision to save money for the future.\nSynonyms: Wise, sensible" },
        { front: "Lament", back: "<strong>To mourn (a person's loss or death).</strong>\n\nExample: She lamented the loss of her childhood home.\nSynonyms: Mourn, bewail" },
        { front: "Languid", back: "<strong>(Of a person, manner, or gesture) having a disinclination for physical exertion or effort; slow and relaxed.</strong>\n\nExample: The languid cat stretched lazily in the sun.\nSynonyms: Relaxed, sluggish" },
        { front: "Laudable", back: "<strong>(Of an action, idea, or aim) deserving praise and commendation.</strong>\n\nExample: Her efforts to help the homeless were laudable.\nSynonyms: Praiseworthy, commendable" },
        { front: "Lavish", back: "<strong>Sumptuously rich, elaborate, or luxurious.</strong>\n\nExample: They hosted a lavish party with expensive food and decorations.\nSynonyms: Extravagant, opulent" },
        { front: "Legitimate", back: "<strong>Conforming to rules or law; able to be defended with logic or justification.</strong>\n\nExample: His excuse for being late was perfectly legitimate.\nSynonyms: Valid, lawful" },
        { front: "Lethargic", back: "<strong>Affected by lethargy; sluggish and apathetic.</strong>\n\nExample: The hot weather made everyone feel lethargic.\nSynonyms: Sluggish, tired" },
        { front: "Levity", back: "<strong>The treatment of a serious matter with humour or lack of due respect.</strong>\n\nExample: He tried to add some levity to the tense meeting with a joke.\nSynonyms: Light-heartedness, cheerfulness" },
        { front: "Liaison", back: "<strong>Communication or cooperation which facilitates a close working relationship between people or organizations.</strong>\n\nExample: She acted as a liaison between the two departments.\nSynonyms: Connection, link" },
        { front: "Lucid", back: "<strong>Expressed clearly; easy to understand.</strong>\n\nExample: The teacher gave a lucid explanation of the complex topic.\nSynonyms: Clear, understandable" },
        { front: "Luminous", back: "<strong>Emitting or reflecting light; shining.</strong>\n\nExample: The full moon was luminous in the night sky.\nSynonyms: Glowing, radiant" }
    ],
    "Set 27": [
        { front: "Magnanimous", back: "<strong>Generous or forgiving, especially towards a rival or less powerful person.</strong>\n\nExample: The magnanimous winner praised his opponent's efforts.\nSynonyms: Generous, benevolent" },
        { front: "Malicious", back: "<strong>Intending or intended to do harm.</strong>\n\nExample: He spread malicious rumors about his competitor.\nSynonyms: Spiteful, malevolent" },
        { front: "Malleable", back: "<strong>(Of a metal or other material) able to be hammered or pressed permanently out of shape without breaking or cracking; easily influenced.</strong>\n\nExample: Clay is a malleable material that can be shaped easily.\nSynonyms: Pliable, adaptable" },
        { front: "Mandate", back: "<strong>An official order or commission to do something.</strong>\n\nExample: The government received a clear mandate from the voters.\nSynonyms: Order, directive" },
        { front: "Manifest", back: "<strong>Clear or obvious to the eye or mind.</strong>\n\nExample: Her joy was manifest in her bright smile.\nSynonyms: Obvious, apparent" },
        { front: "Meander", back: "<strong>(Of a river or road) follow a winding course; (of a person) wander aimlessly.</strong>\n\nExample: The river meandered slowly through the valley.\nSynonyms: Wander, roam" },
        { front: "Melancholy", back: "<strong>A feeling of pensive sadness, typically with no obvious cause.</strong>\n\nExample: The rainy day filled her with a sense of melancholy.\nSynonyms: Sadness, gloom" },
        { front: "Meticulous", back: "<strong>Showing great attention to detail; very careful and precise.</strong>\n\nExample: The artist was meticulous in his painting, ensuring every detail was perfect.\nSynonyms: Detailed, precise" },
        { front: "Mirth", back: "<strong>Amusement, especially as expressed in laughter.</strong>\n\nExample: The party was filled with laughter and mirth.\nSynonyms: Gaiety, glee" },
        { front: "Mitigate", back: "<strong>To make less severe, serious, or painful.</strong>\n\nExample: Wearing a helmet can mitigate the risk of head injuries.\nSynonyms: Alleviate, lessen" },
        { front: "Mundane", back: "<strong>Lacking interest or excitement; dull.</strong>\n\nExample: He found his office job mundane and longed for adventure.\nSynonyms: Dull, routine" }
    ],
    "Set 28": [
        { front: "Nebulous", back: "<strong>(Of a concept or idea) unclear, vague, or ill-defined.</strong>\n\nExample: His explanation of the plan was nebulous and confusing.\nSynonyms: Vague, unclear" },
        { front: "Nefarious", back: "<strong>(Typically of an action or activity) wicked or criminal.</strong>\n\nExample: The nefarious villain plotted to steal the treasure.\nSynonyms: Wicked, evil" },
        { front: "Nihilism", back: "<strong>The rejection of all religious and moral principles, often in the belief that life is meaningless.</strong>\n\nExample: His philosophy was close to nihilism, believing in no inherent value.\nSynonyms: Cynicism, disbelief" },
        { front: "Nominal", back: "<strong>(Of a role or status) existing in name only; (of a price or charge) very small.</strong>\n\nExample: He was only the nominal head of the company, with no real power.\nSynonyms: Titular, minimal" },
        { front: "Nonchalant", back: "<strong>(Of a person or manner) feeling or appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm.</strong>\n\nExample: She tried to act nonchalant, but I knew she was nervous.\nSynonyms: Casual, indifferent" },
        { front: "Noxious", back: "<strong>Harmful, poisonous, or very unpleasant.</strong>\n\nExample: Noxious fumes escaped from the factory, polluting the air.\nSynonyms: Harmful, toxic" },
        { front: "Nuance", back: "<strong>A subtle difference in or shade of meaning, expression, or sound.</strong>\n\nExample: He noticed every nuance in her tone of voice.\nSynonyms: Subtlety, distinction" },
        { front: "Obdurate", back: "<strong>Stubbornly refusing to change one's opinion or course of action.</strong>\n\nExample: The obdurate child refused to eat his vegetables.\nSynonyms: Stubborn, unyielding" },
        { front: "Obliterate", back: "<strong>To destroy utterly; wipe out.</strong>\n\nExample: The bomb obliterated the entire building.\nSynonyms: Destroy, erase" },
        { front: "Obsequious", back: "<strong>Obedient or attentive to an excessive or servile degree.</strong>\n\nExample: The obsequious assistant always agreed with his boss.\nSynonyms: Servile, fawning" },
        { front: "Obtuse", back: "<strong>Annoyingly insensitive or slow to understand.</strong>\n\nExample: He was too obtuse to grasp the subtle hint.\nSynonyms: Stupid, dull" }
    ],
    "Set 29": [
        { front: "Omnipotent", back: "<strong>(Of a deity or other supreme being) having unlimited power; able to do anything.</strong>\n\nExample: In many religions, God is considered omnipotent.\nSynonyms: All-powerful, supreme" },
        { front: "Onerous", back: "<strong>(Of a task, duty, or responsibility) involving an amount of effort, difficulty, or inconvenience that is much greater than one's ability.</strong>\n\nExample: The captain had the onerous task of cleaning the entire ship.\nSynonyms: Burdensome, difficult" },
        { front: "Opaque", back: "<strong>Not able to be seen through; not transparent.</strong>\n\nExample: The opaque glass made it impossible to see inside the room.\nSynonyms: Nontransparent, cloudy" },
        { front: "Opulent", back: "<strong>Rich and luxurious or lavish.</strong>\n\nExample: The opulent mansion was filled with expensive furniture.\nSynonyms: Luxurious, wealthy" },
        { front: "Oscillate", back: "<strong>To swing back and forth with a regular rhythm.</strong>\n\nExample: The pendulum oscillated from side to side.\nSynonyms: Swing, waver" },
        { front: "Ostentatious", back: "<strong>Characterized by vulgar or pretentious display; designed to impress or attract notice.</strong>\n\nExample: She wore an ostentatious diamond necklace to the party.\nSynonyms: Showy, flashy" },
        { front: "Pacify", back: "<strong>To quell the anger, agitation, or excitement of (someone).</strong>\n\nExample: He tried to pacify the crying baby with a lullaby.\nSynonyms: Calm, appease" },
        { front: "Palpable", back: "<strong>(Of a feeling or atmosphere) so intense as to be almost touched or felt.</strong>\n\nExample: There was a palpable tension in the room before the announcement.\nSynonyms: Tangible, perceptible" },
        { front: "Paltry", back: "<strong>(Of an amount) small or meagre.</strong>\n\nExample: He earned a paltry sum for all his hard work.\nSynonyms: Meagre, trivial" },
        { front: "Paradox", back: "<strong>A seemingly absurd or self-contradictory statement or proposition that when investigated or explained may prove to be well founded or true.</strong>\n\nExample: It's a paradox that fighting a war can sometimes bring peace.\nSynonyms: Contradiction, enigma" },
        { front: "Paramount", back: "<strong>More important than anything else; supreme.</strong>\n\nExample: Safety is of paramount importance in construction work.\nSynonyms: Supreme, foremost" }
    ],
    "Set 30": [
        { front: "Pariah", back: "<strong>An outcast.</strong>\n\nExample: After his betrayal, he became a pariah among his friends.\nSynonyms: Outcast, undesirable" },
        { front: "Parsimonious", back: "<strong>Unwilling to spend money or use resources; stingy or frugal.</strong>\n\nExample: He was so parsimonious that he refused to turn on the heating.\nSynonyms: Stingy, frugal" },
        { front: "Patronize", back: "<strong>To treat with an apparent kindness that betrays a feeling of superiority.</strong>\n\nExample: The older student would often patronize the younger ones.\nSynonyms: Condescend, talk down to" },
        { front: "Paucity", back: "<strong>The presence of something only in small or insufficient quantities or amounts; scarcity.</strong>\n\nExample: There was a paucity of evidence to support his claims.\nSynonyms: Scarcity, shortage" },
        { front: "Pensive", back: "<strong>Engaged in, involving, or reflecting deep or serious thought.</strong>\n\nExample: He looked pensive as he stared out the window, deep in thought.\nSynonyms: Thoughtful, reflective" },
        { front: "Perfidious", back: "<strong>Deceitful and untrustworthy.</strong>\n\nExample: The perfidious friend betrayed their secret.\nSynonyms: Treacherous, disloyal" },
        { front: "Permeate", back: "<strong>To spread throughout (something); pervade.</strong>\n\nExample: The smell of freshly baked bread permeated the entire house.\nSynonyms: Pervade, spread through" },
        { front: "Perplexed", back: "<strong>Completely baffled; very puzzled.</strong>\n\nExample: She looked perplexed by the difficult math problem.\nSynonyms: Puzzled, confused" },
        { front: "Pertinent", back: "<strong>Relevant or applicable to a particular matter; apposite.</strong>\n\nExample: Please stick to the pertinent details in your report.\nSynonyms: Relevant, applicable" },
        { front: "Philanthropy", back: "<strong>The desire to promote the welfare of others, expressed especially by the generous donation of money to good causes.</strong>\n\nExample: His acts of philanthropy helped many struggling charities.\nSynonyms: Generosity, charity" },
        { front: "Pious", back: "<strong>Devoutly religious.</strong>\n\nExample: The pious monk spent his days in prayer and meditation.\nSynonyms: Religious, devout" }
    ],
// vocab-data.js - Part 4 of 4

    "Set 31": [
        { front: "Placid", back: "<strong>Calm and peaceful, with little movement or activity.</strong>\n\nExample: The placid lake reflected the clear blue sky.\nSynonyms: Calm, tranquil" },
        { front: "Plausible", back: "<strong>(Of an argument or statement) seeming reasonable or probable.</strong>\n\nExample: His excuse for being late was plausible.\nSynonyms: Believable, credible" },
        { front: "Plethora", back: "<strong>A large or excessive amount of something.</strong>\n\nExample: There was a plethora of options on the menu.\nSynonyms: Excess, abundance" },
        { front: "Pliable", back: "<strong>Easily bent; flexible.</strong>\n\nExample: The pliable clay was easy to shape.\nSynonyms: Flexible, supple" },
        { front: "Poignant", back: "<strong>Evoking a keen sense of sadness or regret.</strong>\n\nExample: The poignant film about the war made everyone cry.\nSynonyms: Touching, moving" },
        { front: "Pompous", back: "<strong>Feeling or showing that you are much more important than other people.</strong>\n\nExample: The pompous official spoke in a very arrogant tone.\nSynonyms: Arrogant, self-important" },
        { front: "Precarious", back: "<strong>Not securely held or in position; dangerously likely to fall or collapse.</strong>\n\nExample: He made a precarious living as an artist.\nSynonyms: Uncertain, insecure" },
        { front: "Precocious", back: "<strong>(Of a child) having developed certain abilities or inclinations at an earlier age than usual.</strong>\n\nExample: The precocious child could read at the age of three.\nSynonyms: Advanced, gifted" },
        { front: "Prodigal", back: "<strong>Spending money or resources freely and recklessly; wastefully extravagant.</strong>\n\nExample: The prodigal son returned home after wasting all his money.\nSynonyms: Wasteful, extravagant" },
        { front: "Prodigious", back: "<strong>Remarkably or impressively great in extent, size, or degree.</strong>\n\nExample: He had a prodigious appetite, eating six sandwiches for lunch.\nSynonyms: Enormous, huge" },
        { front: "Quell", back: "<strong>To put an end to (a rebellion or other disorder), typically by the use of force.</strong>\n\nExample: The police were called in to quell the riot.\nSynonyms: Suppress, crush" }
    ],
    "Set 32": [
        { front: "Querulous", back: "<strong>Complaining in a petulant or whining manner.</strong>\n\nExample: The querulous child was always unhappy with his toys.\nSynonyms: Whining, complaining" },
        { front: "Quibble", back: "<strong>To argue or raise objections about a trivial matter.</strong>\n\nExample: They were quibbling over who should pay the small bill.\nSynonyms: Argue, bicker" },
        { front: "Rambunctious", back: "<strong>Uncontrollably exuberant; boisterous.</strong>\n\nExample: The rambunctious children were running and shouting in the playground.\nSynonyms: Boisterous, rowdy" },
        { front: "Rancour", back: "<strong>Long-standing bitterness or resentment.</strong>\n\nExample: He felt great rancour towards the person who had betrayed him.\nSynonyms: Bitterness, spite" },
        { front: "Rapport", back: "<strong>A close and harmonious relationship in which the people or groups concerned understand each other's feelings or ideas and communicate well.</strong>\n\nExample: The teacher built a good rapport with her students.\nSynonyms: Bond, understanding" },
        { front: "Ratify", back: "<strong>To sign or give formal consent to (a treaty, contract, or agreement), making it officially valid.</strong>\n\nExample: The government decided to ratify the new trade agreement.\nSynonyms: Approve, confirm" },
        { front: "Raucous", back: "<strong>Making a disturbingly harsh and loud noise.</strong>\n\nExample: The raucous laughter from the next room was very distracting.\nSynonyms: Harsh, loud" },
        { front: "Rebuke", back: "<strong>To express sharp disapproval or criticism of (someone) because of their behaviour or actions.</strong>\n\nExample: The mother rebuked her child for being rude.\nSynonyms: Reprimand, scold" },
        { front: "Recalcitrant", back: "<strong>Having an obstinately uncooperative attitude towards authority or discipline.</strong>\n\nExample: The recalcitrant student refused to do any work.\nSynonyms: Uncooperative, rebellious" },
        { front: "Reciprocate", back: "<strong>To respond to (a gesture or action) by making a corresponding one.</strong>\n\nExample: She did not reciprocate his feelings of affection.\nSynonyms: Return, match" },
        { front: "Recluse", back: "<strong>A person who lives a solitary life and tends to avoid other people.</strong>\n\nExample: The famous author became a recluse, rarely leaving his home.\nSynonyms: Hermit, loner" }
    ],
    "Set 33": [
        { front: "Reconcile", back: "<strong>To restore friendly relations between.</strong>\n\nExample: The two friends finally reconciled after their long argument.\nSynonyms: Reunite, patch up" },
        { front: "Redundant", back: "<strong>Not or no longer needed or useful; superfluous.</strong>\n\nExample: The new computer system made his old job redundant.\nSynonyms: Unnecessary, superfluous" },
        { front: "Refute", back: "<strong>To prove (a statement or theory) to be wrong or false; disprove.</strong>\n\nExample: The lawyer used evidence to refute the witness's claims.\nSynonyms: Disprove, debunk" },
        { front: "Relevant", back: "<strong>Closely connected or appropriate to what is being done or considered.</strong>\n\nExample: Please only provide information that is relevant to the case.\nSynonyms: Pertinent, applicable" },
        { front: "Replete", back: "<strong>Filled or well-supplied with something.</strong>\n\nExample: The book was replete with interesting facts and figures.\nSynonyms: Filled, full" },
        { front: "Reprehensible", back: "<strong>Deserving censure or condemnation.</strong>\n\nExample: His selfish behavior was reprehensible.\nSynonyms: Deplorable, disgraceful" },
        { front: "Repudiate", back: "<strong>To refuse to accept or be associated with.</strong>\n\nExample: He repudiated the accusations made against him.\nSynonyms: Reject, renounce" },
        { front: "Rescind", back: "<strong>To revoke, cancel, or repeal (a law, order, or agreement).</strong>\n\nExample: The company decided to rescind the job offer.\nSynonyms: Revoke, cancel" },
        { front: "Reticent", back: "<strong>Not revealing one's thoughts or feelings readily.</strong>\n\nExample: He was very reticent about his personal life.\nSynonyms: Reserved, quiet" },
        { front: "Revere", back: "<strong>To feel deep respect or admiration for (something).</strong>\n\nExample: The students revere their inspiring teacher.\nSynonyms: Admire, respect" },
        { front: "Sagacious", back: "<strong>Having or showing keen mental discernment and good judgment; wise.</strong>\n\nExample: The sagacious old woman gave him excellent advice.\nSynonyms: Wise, clever" }
    ],
    "Set 34": [
        { front: "Salient", back: "<strong>Most noticeable or important.</strong>\n\nExample: He clearly summarized the salient points of the argument.\nSynonyms: Important, main" },
        { front: "Sanguine", back: "<strong>Optimistic or positive, especially in an apparently bad or difficult situation.</strong>\n\nExample: He remained sanguine about his chances of success.\nSynonyms: Optimistic, hopeful" },
        { front: "Scrutinize", back: "<strong>To examine or inspect closely and thoroughly.</strong>\n\nExample: The detective scrutinized the evidence for any clues.\nSynonyms: Inspect, examine" },
        { front: "Spurious", back: "<strong>Not being what it purports to be; false or fake.</strong>\n\nExample: He was arrested for making spurious claims about his identity.\nSynonyms: Fake, false" },
        { front: "Stoic", back: "<strong>A person who can endure pain or hardship without showing their feelings or complaining.</strong>\n\nExample: He remained stoic even when he heard the bad news.\nSynonyms: Unemotional, impassive" },
        { front: "Substantiate", back: "<strong>To provide evidence to support or prove the truth of.</strong>\n\nExample: You must substantiate your claims with facts.\nSynonyms: Prove, support" },
        { front: "Subtle", back: "<strong>(Especially of a change or distinction) so delicate or precise as to be difficult to analyze or describe.</strong>\n\nExample: There was a subtle change in her tone of voice.\nSynonyms: Faint, delicate" },
        { front: "Superfluous", back: "<strong>Unnecessary, especially through being more than enough.</strong>\n\nExample: Please remove any superfluous details from your summary.\nSynonyms: Unnecessary, redundant" },
        { front: "Sycophant", back: "<strong>A person who acts obsequiously towards someone important in order to gain advantage.</strong>\n\nExample: The king was surrounded by sycophants who always agreed with him.\nSynonyms: Flatterer, lackey" },
        { front: "Tactful", back: "<strong>Having or showing skill and sensitivity in dealing with others or with difficult issues.</strong>\n\nExample: She gave a tactful reply to the awkward question.\nSynonyms: Diplomatic, discreet" },
        { front: "Tenable", back: "<strong>Able to be maintained or defended against attack or objection.</strong>\n\nExample: His argument was not tenable and was easily refuted.\nSynonyms: Defensible, justifiable" }
    ],
    "Set 35": [
        { front: "Terse", back: "<strong>Sparing in the use of words; abrupt.</strong>\n\nExample: His terse reply of 'No' ended the conversation.\nSynonyms: Curt, brief" },
        { front: "Transient", back: "<strong>Lasting only for a short time; impermanent.</strong>\n\nExample: The transient beauty of the cherry blossoms lasts only a week.\nSynonyms: Fleeting, temporary" },
        { front: "Trepidation", back: "<strong>A feeling of fear or anxiety about something that may happen.</strong>\n\nExample: He felt great trepidation before his first public speech.\nSynonyms: Fear, apprehension" },
        { front: "Trite", back: "<strong>(Of a remark, opinion, or idea) overused and consequently of little import; lacking originality or freshness.</strong>\n\nExample: His speech was full of trite clichés about teamwork.\nSynonyms: Overused, unoriginal" },
        { front: "Truncate", back: "<strong>To shorten (something) by cutting off the top or the end.</strong>\n\nExample: The article was truncated to fit the small space in the newspaper.\nSynonyms: Shorten, cut" },
        { front: "Ubiquitous", back: "<strong>Present, appearing, or found everywhere.</strong>\n\nExample: Smartphones are now ubiquitous all over the world.\nSynonyms: Everywhere, pervasive" },
        { front: "Unprecedented", back: "<strong>Never done or known before.</strong>\n\nExample: The pandemic caused an unprecedented shift to remote work.\nSynonyms: Unheard-of, novel" },
        { front: "Usurp", back: "<strong>To take (a position of power or importance) illegally or by force.</strong>\n\nExample: The general tried to usurp the king's throne.\nSynonyms: Seize, take over" },
        { front: "Vacillate", back: "<strong>To waver between different opinions or actions; be indecisive.</strong>\n\nExample: He vacillated between choosing the red car and the blue one.\nSynonyms: Waver, hesitate" },
        { front: "Validate", back: "<strong>To check or prove the validity or accuracy of (something).</strong>\n\nExample: You must validate your parking ticket before you leave.\nSynonyms: Confirm, approve" },
        { front: "Vehement", back: "<strong>Showing strong feeling; forceful, passionate, or intense.</strong>\n\nExample: She was vehement in her denial of the accusations.\nSynonyms: Passionate, forceful" }
    ],
    "Set 36": [
        { front: "Verbose", back: "<strong>Using or expressed in more words than are needed.</strong>\n\nExample: His verbose explanation was confusing and unnecessarily long.\nSynonyms: Wordy, long-winded" },
        { front: "Vestige", back: "<strong>A trace of something that is disappearing or no longer exists.</strong>\n\nExample: The old wall was the last vestige of the ancient city.\nSynonyms: Trace, remnant" },
        { front: "Vilify", back: "<strong>To speak or write about in an abusively disparaging manner.</strong>\n\nExample: The media began to vilify the politician after the scandal.\nSynonyms: Disparage, slander" },
        { front: "Vindicate", back: "<strong>To clear (someone) of blame or suspicion.</strong>\n\nExample: The new evidence served to vindicate the wrongly accused man.\nSynonyms: Acquit, clear" },
        { front: "Virtuoso", back: "<strong>A person highly skilled in music or another artistic pursuit.</strong>\n\nExample: The violin virtuoso played the complex piece perfectly.\nSynonyms: Genius, expert" },
        { front: "Vivacious", back: "<strong>(Especially of a woman) attractively lively and animated.</strong>\n\nExample: Her vivacious personality made her the life of the party.\nSynonyms: Lively, spirited" },
        { front: "Volatile", back: "<strong>Liable to change rapidly and unpredictably, especially for the worse.</strong>\n\nExample: The political situation in the country is very volatile.\nSynonyms: Unstable, unpredictable" },
        { front: "Wane", back: "<strong>(Of the moon) have a progressively smaller part of its visible surface illuminated; (of a state or feeling) decrease in vigour or extent.</strong>\n\nExample: His enthusiasm for the project began to wane.\nSynonyms: Decrease, dwindle" },
        { front: "Wary", back: "<strong>Feeling or showing caution about possible dangers or problems.</strong>\n\nExample: Be wary of strangers offering you gifts.\nSynonyms: Cautious, careful" },
        { front: "Zealot", back: "<strong>A person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.</strong>\n\nExample: The religious zealot refused to listen to any other viewpoints.\nSynonyms: Fanatic, extremist" },
        { front: "Zenith", back: "<strong>The time at which something is most powerful or successful.</strong>\n\nExample: The empire reached its zenith in the 19th century.\nSynonyms: Peak, pinnacle" }
    ]
}
